{{- if (.Values.network.hostname) }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: gateway
    namespace: cilium
  hostnames:
  - {{ $.Values.network.hostname  }}
  rules:
    - backendRefs:
      - name: {{ include "app.fullname" $ }} # svc name
        port: {{ 443 }}
{{- end }}
---
{{- if (.Values.network.tcp) }}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: gateway
    namespace: cilium
  rules:
  - backendRefs:
    {{- range .Values.network.tcp }}
    - name: {{ include "app.fullname" $ }} # svc name
      port: {{ . }}
    {{- end }}
{{- end }}