{{- range .Values.storage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
spec:
  storageClassName: {{ .storageClassName }}
  accessModes:
    {{- toYaml .accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .size }}
{{- end }}